//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_Projekt_EH515M
{
    using System;
    using System.Collections.Generic;
    
    public partial class Futár
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Futár()
        {
            this.Rendelés = new HashSet<Rendelés>();
        }
    
        public int FutárSK { get; set; }
        public string Név { get; set; }
        public bool Foglalt { get; set; }
        public string Telefonszám { get; set; }
        public int Jármű { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rendelés> Rendelés { get; set; }
    }
}
