//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_Projekt_EH515M
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rendelés
    {
        public int RendelésID { get; set; }
        public int Ár { get; set; }
        public System.DateTime Rögzítés { get; set; }
        public System.DateTime Elfogadva { get; set; }
        public System.DateTime Felvéve { get; set; }
        public System.DateTime Leadva { get; set; }
        public int Késés { get; set; }
        public int FutárFK { get; set; }
        public int ÉtteremFK { get; set; }
        public bool Aktív { get; set; }
    
        public virtual Étterem Étterem { get; set; }
        public virtual Futár Futár { get; set; }
    }
}
